# requiring the environment of NodeJS 8.9.x LTS (carbon)
image: node:8.9

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

before_script:
  - cd website
  - npm install
  
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  script:
    - npm run build
    - cd ..
    - mkdir public
    - mv website/build/study/* public
    - mv public/en/* *
  artifacts:
    paths:
      - public
  only:
    - master
